package com.university.manager.services;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
//CreatedAndDevelopedByWassimKhazri
//https://www.linkedin.com/in/wassim-khazri-ab923a14b/
import java.text.SimpleDateFormat;
import java.util.Date;

public class HeaderFooterPageEvent extends PdfPageEventHelper {

	@Override
	public void onEndPage(PdfWriter writer, Document document) {
		PdfPTable footer = new PdfPTable(2);
		try {
			footer.setWidths(new int[] { 24, 2 });
			footer.setTotalWidth(800);
			footer.setLockedWidth(true);
			footer.getDefaultCell().setFixedHeight(20);
			footer.getDefaultCell().setBorder(Rectangle.TOP);
			footer.addCell(
					"Generated by Wassim Khazri - " + new SimpleDateFormat("yyyy-MM-dd HH:mm").format(new Date()));
			footer.getDefaultCell().setHorizontalAlignment(Element.ALIGN_RIGHT);
			footer.addCell("Page " + writer.getPageNumber());
			footer.writeSelectedRows(0, -1, 34, 30, writer.getDirectContent());
		} catch (DocumentException de) {
			throw new ExceptionConverter(de);
		}
	}
}
